config/routes.rb
Conteo::Application.routes.draw do

  devise_for :users
  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'

  match '/api', to: 'home#api'

  match '/&fref=fb', to: 'home#index'
  match '/auth/:provider/callback', to: 'authentications#create'

  match '/casillas/:estado/:section', to: 'buscar_casillas#show', as: 'buscar_casillas_show'
  match '/casillas/buscar', to: 'buscar_casillas#new', via: :get


  resource :buscar_casillas, only: [:new, :show, :create], path: '/casillas/buscar'

  resources :exit_polls, only: :create
  resources :casillas, only: [:show, :update, :create] do
    resources :tickets, only: [:create], path: '/tickets/new'
  end

  resources :faltantes, only: [:index]

  match '/faltantes/:estado', to: 'faltantes#show', as: 'faltante'
  match '/faltantes/:estado/:page', to: 'faltantes#show', as: 'faltante'

  match '/verificacion', to: 'verificacion#show', as: 'verificacion'
  match '/verificacion/:id', to: 'verificacion#update', as: 'verificacion', via: :put

  namespace :admin do
    root to: 'panel#index'
    resources :verifications, only: :index
    resources :boxes do
      resource :results, only: [:show, :update, :create]
    end

    resources :result_images, only: :update

    resources :admins
    resources :tickets, only: [:index, :create, :update, :destroy]
  end

  namespace :api do
    resources :casillas, only: [:index, :show]
  end

  mount Resque::Server.new, :at => "/resque"
  match '/images/logo-desktop.png' => redirect('/assets/main-img.png')
end

app/models/result.rb
class Result < ActiveRecord::Base

  #
  # Attributes Accesors
  #
  attr_accessible :box_id, :movimiento_ciudadano, :nueva_alianza, :null, :others, :pan, :prd, :pri, :pt, :pvem, :pri_pvem, :prd_pt_mc, :prd_pt, :prd_mc, :pt_mc

  #
  # Relations
  #
  belongs_to :box

  #
  # State Machine
  #
  state_machine :state, :initial => :new do
    state :ready_to_revision
    state :pre_verified
    state :verified
    state :rejected
    state :reported

    event :back do
      transition ready_to_revision: :new
    end

    event :pre_approved do
      transition [:ready_to_revision] => :pre_verified
    end

    event :filled do
      transition new: :ready_to_revision
    end

    event :approved do
      transition [:ready_to_revision, :rejected, :reported, :pre_verified] => :verified
    end

    event :rejecting do
      transition ready_to_revision: :rejected
    end

    event :reporting do
      transition verified: :reported
    end
  end

  #
  # Simple audit
  #
  simple_audit username_method: :email do |result|
    {
      movimiento_ciudadano: result.movimiento_ciudadano,
      nueva_alianza: result.nueva_alianza,
      null: result.null,
      others: result.others,
      pan: result.pan,
      prd: result.prd,
      pri: result.pri,
      pt: result.pt,
      pvem: result.pvem,
      pri_pvem: result.pri_pvem,
      prd_pt_mc: result.prd_pt_mc,
      prd_pt: result.prd_pt,
      prd_mc: result.prd_mc,
      pt_mc: result.pt_mc
    }
  end

  def self.count_total
    self.count
  end

  def self.count_to_verified
    where(state: 'ready_to_revision').count
  end

  def self.count_verified
    where(state: 'verified').count
  end

  def self.count_rejected
    where(state: 'rejected').count
  end

  def captured?
    (pan||0) > 0 && (pri||0) > 0 && (prd||0) > 0
  end
end

app/controllers/admin/results_controller.rb
class Admin::ResultsController < Admin::BaseController
  load_and_authorize_resource

  def show
    @result = casilla.result.present? ? casilla.result : casilla.build_result
  end

  def create
    @result = casilla.build_result(params[:result])
    if @result.save
      @result.approved! if @result.can_approved?
      redirect_to admin_root_url, flash: {notice: 'La casilla fue verificada.'}
    else
      render :show, flash: {error: 'Ocurrio un error al verificar las casilla.'}
    end
  end

  def update
    if casilla.result.update_attributes(params[:result])
      casilla.result.approved! if casilla.result.can_approved?
      redirect_to admin_root_url, flash: {notice: 'La casilla fue verificada.'}
    else
      render :show, flash: {error: 'Ocurrio un error al verificar las casilla.'}
    end
  end

  private

  def casilla
    @casilla ||= CasillaPresenter.new Box.find(params[:box_id])
  end
end

app/views/admin/results/show.html.haml
.row-fluid
  .span12.well
    .row-fluid
      %strong.span3
        Casilla:
      .span3
        = @casilla.kind_and_number
      %strong.span3
        Sección:
      .span3
        = @casilla.section

    .row-fluid
      %strong.span3
        Delegación/Municipio:
      .span3
        = @casilla.district_head
      %strong.span3
        Estado:
      .span3
        = @casilla.state_name

    .row-fluid
      %strong.span3
        Ubicación:
      .span9
        = @casilla.complete_address

.row-fluid
  .span6.well
    = form_for [:admin, @casilla, @result], url: admin_box_results_path(box_id: @casilla.id) do |form|
      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_pan.png"
          .span6
            = form.number_field :pan, class: :span12, tabindex: 1

        .span6
          .span6
            = image_tag '/assets/logo_pri.png'
          .span6
            = form.number_field :pri, class: :span12, tabindex: 2

      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_prd.png"
          .span6
            =form.number_field :prd, class: :span12, tabindex: 3

        .span6
          .span6
            = image_tag "/assets/logo_vem.png"
          .span6
            = form.number_field :pvem, class: :span12, tabindex: 4

      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_pt.jpg"
          .span6
            = form.number_field :pt, class: :span12, tabindex: 5

        .span6
          .span6
            = image_tag "/assets/logo_movimiento_ciudadano.jpg"
          .span6
            = form.number_field :movimiento_ciudadano, class: :span12, tabindex: 6

      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_nueva_alianza.png"
          .span6
            = form.number_field :nueva_alianza, class: :span12, tabindex: 7

        .span6
          .span6
            = image_tag "/assets/logo_pri.png"
            = image_tag "/assets/logo_vem.png"
          .span6
            = form.number_field :pri_pvem, class: :span12, tabindex: 8

      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_prd.png", class: :span4
            = image_tag "/assets/logo_pt.jpg", class: :span4
            = image_tag "/assets/logo_movimiento_ciudadano.jpg", class: :span4
          .span6
            = form.number_field :prd_pt_mc, class: :span12, tabindex: 9

        .span6
          .span6
            = image_tag "/assets/logo_prd.png"
            = image_tag "/assets/logo_pt.jpg"
          .span6
            = form.number_field :prd_pt, class: :span12, tabindex: 10

      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_prd.png"
            = image_tag "/assets/logo_movimiento_ciudadano.jpg"
          .span6
            = form.number_field :prd_mc, class: :span12, tabindex: 11

        .span6
          .span6
            = image_tag "/assets/logo_pt.jpg"
            = image_tag "/assets/logo_movimiento_ciudadano.jpg"
          .span6
            = form.number_field :pt_mc, class: :span12, tabindex: 12

      .row-fluid
        .span6
          .span6
            = image_tag "/assets/logo_otro_candidato.png"
          .span6
            = form.number_field :others, class: :span12, tabindex: 13

        .span6
          .span6
            = image_tag "/assets/logo_votos_nulos.png"
          .span6
            =form.number_field :null, class: :span12, tabindex: 14

      .row-fluid
        .span6
          .row-fluid
            %strong.span6
              Lista Nominal:
            .span6
              = @casilla.nominal_list
        .span6
          .row-fluid
            %strong.span6
              Total casilla:
            .span6#total-casilla

      .row-fluid
        .span6
          = form.submit 'Enviar/Verificar', class: 'btn btn-primary', tabindex: 15
          %i{class: 'icon-question-sign', id: 'popover-verified'}
        .span6
          .btn-group
            %a{class: "btn btn-danger dropdown-toggle", "data-toggle" => "dropdown", href: "#"}
              Rechazar
              %span{class: "caret"}
            %ul{class: "dropdown-menu"}
              %li
                = link_to 'Falta Fotografia', admin_tickets_path(box_id: @casilla.id, reason: 'missing_photo'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Falta Fotografia"?'}
              %li
                = link_to 'Fotografia alterada', admin_tickets_path(box_id: @casilla.id, reason: 'photo_altered'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Fotografia alterada"?'}
              %li
                = link_to 'Información dudosa', admin_tickets_path(box_id: @casilla.id, reason: 'dubious_information'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Información dudosa"?'}
              %li
                = link_to 'Casilla sospechosa', admin_tickets_path(box_id: @casilla.id, reason: 'suspicious_box'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Casilla sospechosa"?'}
              %li
                = link_to 'Sobrevotación', admin_tickets_path(box_id: @casilla.id, reason: 'overvoting'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Sobrevotación"?'}
              %li
                = link_to 'Casilla no instalada', admin_tickets_path(box_id: @casilla.id, reason: 'box_not_installed'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Casilla no instalada"?'}
              %li
                = link_to 'Ilegible', admin_tickets_path(box_id: @casilla.id, reason: 'photo_illegible'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Ilegible"?'}


          %i{class: 'icon-question-sign', id: 'popover-tickets'}
  .span6.well
    %h2
      Fotos de casillas

    - @casilla.result_images.each_with_index do |image, index|
      .row-fluid
        .span12
          Foto #{index + 1}
          = link_to '#', class: 'hide-map', 'data-map-id' => index do
            %i{class: "icon-chevron-up"}
          = link_to '#', class: 'show-map', 'data-map-id' => index do
            %i{class: "icon-chevron-down"}
      .row-fluid
        .span12.foto-details{id: "map-#{index}"}
          .row-fluid
            .span12
              %a{href: '#', id: 'rotate-left', class: 'btn btn-primary float-left', 'data-image-index' => index}
                %i{class: 'icon-arrow-left'}
                Girar izquierda
              %a{href: '#', id: 'rotate-right', class: 'btn btn-primary float-right', 'data-image-index' => index}
                Girar derecha
                %i{class: 'icon-arrow-right'}
          .row-fluid
            .span12
              = image_tag image.blanket, id: "image-#{index}"
          .row-fluid
            .span6
              %label
                Modelo:
              = image.exif[:model]
            .span6
              %label
                Tomada el:
              = image.exif[:date_time]
          .row-fluid
            .span6
              %label
                Fabricante
              = image.exif[:manufacturer]
            .span6
              %label
                Compresión:
              = image.exif[:compression]
          .row-fluid
            .span6
              %label
                Resolución:
              = image.exif[:resolution]
            .span6
              %label
                Software:
              = image.exif[:software]

          .row-fluid
            .span12
              %h4
                Cambiar de casilla
              = form_tag admin_boxes_path(:format => :json), class: 'form-inline', remote: true, method: :get, id: 'search-boxes' do
                = select_tag :state, options_from_collection_for_select(State.all, :id, :name)
                = text_field_tag :section, ''
                = submit_tag 'Buscar', class: [:btn, 'btn-primary']

          .row-fluid#update-image
            .span12
              = form_tag admin_result_image_path(image), class: 'form-horizontal hide', method: :put, id: 'update-result-image' do

                = submit_tag 'Enviar', class: [:btn, 'btn-primary']

          - if image.exif[:location]
            .row-fluid
              .span12.box-map{id: "box-map-#{index}"}
            %script
              $(document).ready(function() {
              google_maps = GoogleMaps.initialize(#{image.exif[:location].merge({map_id: "box-map-#{index}"}).to_json.html_safe})
              google_maps.rendeWithCoordinates();
              });

.row-fluid#tickets-div
  .span12
    .accordion-group
      .accordion-heading
        %a{class: "accordion-toggle", 'data-toggle' => "collapse", 'data-parent' => 'tickets-div', href: "#collapseOne"}
          Historial de cambios

      #collapseOne.accordion-body.collapse.out
        .accordion-inner
          = render_audits @result

%script#box-templete
  <div class='control-group'>
  <label class='control-label'>
  <%= kind %> <%= number %>
  </label>
  <div class='controls'>
  <input name="casilla_id" type="radio" value="<%= id %>" />
  </div>
  </div>