config/routes.rb
Conteo::Application.routes.draw do

  devise_for :users
  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'

  match '/api', to: 'home#api'

  match '/&fref=fb', to: 'home#index'
  match '/auth/:provider/callback', to: 'authentications#create'

  match '/casillas/:estado/:section', to: 'buscar_casillas#show', as: 'buscar_casillas_show'
  match '/casillas/buscar', to: 'buscar_casillas#new', via: :get


  resource :buscar_casillas, only: [:new, :show, :create], path: '/casillas/buscar'

  resources :exit_polls, only: :create
  resources :casillas, only: [:show, :update, :create] do
    resources :tickets, only: [:create], path: '/tickets/new'
  end

  resources :faltantes, only: [:index]

  match '/faltantes/:estado', to: 'faltantes#show', as: 'faltante'
  match '/faltantes/:estado/:page', to: 'faltantes#show', as: 'faltante'

  match '/verificacion', to: 'verificacion#show', as: 'verificacion'
  match '/verificacion/:id', to: 'verificacion#update', as: 'verificacion', via: :put

  namespace :admin do
    root to: 'panel#index'
    resources :verifications, only: :index
    resources :boxes do
      resource :results, only: [:show, :update, :create]
    end

    resources :result_images, only: :update

    resources :admins
    resources :tickets, only: [:index, :create, :update, :destroy]
  end

  namespace :api do
    resources :casillas, only: [:index, :show]
  end

  mount Resque::Server.new, :at => "/resque"
  match '/images/logo-desktop.png' => redirect('/assets/main-img.png')
end

app/controllers/verificacion_controller.rb
class VerificacionController < ApplicationController
  def show
    @casilla = CasillaPresenter.new(Box.to_verified.offset(rand(Box.to_verified.count)).first, current_user)
  end

  def update
    box = CasillaPresenter.new Box.find(params[:id]), current_user
    box.verified!
    redirect_to action: :show
  end
end

app/helpers/verificacion_helper.rb
module VerificacionHelper
end

app/views/verificacion/show.html.haml
.row-fluid
  .span12.alert
    %ol
      %li
        Asegurarse que la fotografía pertenezca a la casilla. Que el estado, la sección y el tipo de casilla concuerden.
      %li
        Los votos deben de coincidir con las fotografía.
      %li
        Los votos emitidos no deben de exceder la lista nominal.
    Como candado se seguridad cada casilla tiene que verificada por dos usuarios diferente con ip's diferente.

.row-fluid
  .span12.well
    .row-fluid
      %strong.span3
        Casilla:
      .span3
        = @casilla.kind_and_number
      %strong.span3
        Sección:
      .span3
        = @casilla.section

    .row-fluid
      %strong.span3
        Delegación/Municipio:
      .span3
        = @casilla.district_head
      %strong.span3
        Estado:
      .span3
        = @casilla.state_name

    .row-fluid
      %strong.span3
        Ubicación:
      .span9
        = @casilla.complete_address

.row-fluid
  .span6
    .row-fluid
      .span12.well
        = render :partial => ((@casilla.result.try(:ready_to_revision?) and current_user) ? '/casillas/results_form' : '/casillas/results'), locals: {form_url: verificacion_path(@casilla.id)}

    .row-fluid
      .span12.well
        .row-fluid
          .span6
            .row-fluid
              .span6
                Lista nominal:
              .span6
                = @casilla.nominal_list
          .span6
            .row-fluid
              .span6
                Votos en la casilla:
              .span6
                #total-casilla
        .row-fluid
          .span12
            .btn-group
              - if current_user
                %a{class: "btn btn-danger dropdown-toggle", "data-toggle" => "dropdown", href: "#"}
                  Reportar Casilla
                  %span{class: "caret"}
                %ul{class: "dropdown-menu"}
                  %li
                    = link_to 'Falta Fotografia', casilla_tickets_path(casilla_id: @casilla.id, reason: 'missing_photo'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Falta Fotografia"?'}
                  %li
                    = link_to 'Fotografia alterada', casilla_tickets_path(casilla_id: @casilla.id, reason: 'photo_altered'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Fotografia alterada"?'}
                  %li
                    = link_to 'Información dudosa', casilla_tickets_path(casilla_id: @casilla.id, reason: 'dubious_information'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Información dudosa"?'}
                  %li
                    = link_to 'Casilla sospechosa', casilla_tickets_path(casilla_id: @casilla.id, reason: 'suspicious_box'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Casilla sospechosa"?'}
                  %li
                    = link_to 'Sobrevotación', casilla_tickets_path(casilla_id: @casilla.id, reason: 'overvoting'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Sobrevotación"?'}
                  %li
                    = link_to 'Casilla no instalada', casilla_tickets_path(casilla_id: @casilla.id, reason: 'box_not_installed'), method: :post, data: {confirm: '¿Seguro desea reportar la casilla como "Casilla no instalada"?'}

                %i{class: 'icon-question-sign', id: 'popover-tickets'}

  .span6.well
    - @casilla.result_images.each do |result_image|
      .zoom-small-image
        = link_to result_image.blanket.url, target: '_blank' do
          = image_tag result_image.blanket.url, class: :span12