config/routes.rb
Conteo::Application.routes.draw do

  devise_for :users
  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'

  match '/api', to: 'home#api'

  match '/&fref=fb', to: 'home#index'
  match '/auth/:provider/callback', to: 'authentications#create'

  match '/casillas/:estado/:section', to: 'buscar_casillas#show', as: 'buscar_casillas_show'
  match '/casillas/buscar', to: 'buscar_casillas#new', via: :get


  resource :buscar_casillas, only: [:new, :show, :create], path: '/casillas/buscar'

  resources :exit_polls, only: :create
  resources :casillas, only: [:show, :update, :create] do
    resources :tickets, only: [:create], path: '/tickets/new'
  end

  resources :faltantes, only: [:index]

  match '/faltantes/:estado', to: 'faltantes#show', as: 'faltante'
  match '/faltantes/:estado/:page', to: 'faltantes#show', as: 'faltante'

  match '/verificacion', to: 'verificacion#show', as: 'verificacion'
  match '/verificacion/:id', to: 'verificacion#update', as: 'verificacion', via: :put

  namespace :admin do
    root to: 'panel#index'
    resources :verifications, only: :index
    resources :boxes do
      resource :results, only: [:show, :update, :create]
    end

    resources :result_images, only: :update

    resources :admins
    resources :tickets, only: [:index, :create, :update, :destroy]
  end

  namespace :api do
    resources :casillas, only: [:index, :show]
  end

  mount Resque::Server.new, :at => "/resque"
  match '/images/logo-desktop.png' => redirect('/assets/main-img.png')
end

app/views/admin/admins/_form.html.haml
= form_for([:admin, @admin]) do |f|
  -if @admin.errors.any?
    %div{:id=>'error_explanation'}
      %h2=pluralize(@admin.errors.count, "error")

      %ul
        -@admin.errors.full_messages.each do |msg|
          %li= msg

  %div
    = f.label :email
    %br
    = f.text_field :email
        
  %div
    = f.label :password
    %br
    = f.password_field :password
   
  %div
    = f.label :"comfirmar password"
    %br
    = f.password_field :password_confirmation
    
  %div
    = f.label :Role
    %br
    = f.collection_select :role, Admin::ROLES, :to_s, :humanize,:include_blank=>true

  %div
    = f.submit

app/views/admin/admins/edit.html.haml
%h1 Editing user
= render 'form'

= link_to 'Show', admin_admin_path(@admin)
= link_to 'Back', admin_admins_path

app/views/admin/admins/index.html.haml
%h1
  Administradores

%p
  = link_to 'Nuevo Administrador', new_admin_admin_path, class: [:btn, 'btn-primary']

%table.table.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th Email
      %th Rol
      %th Acciones
  %tbody
    -@admins.each do |admin|
      %tr
        %td= admin.email
        %td= admin.role
        %td
          %ul
            %li
              = link_to 'Ver', admin_admin_path(admin)
            %li
              = link_to 'Editar', edit_admin_admin_path(admin)
            %li
              = link_to 'Eliminar', admin_admin_path(admin), :confirm => '¿Esta seguro qur desea eliminar al administrador?', :method => :delete

app/views/admin/admins/new.html.haml
%h1 New user
= render 'form'
= link_to 'Back', admin_admins_path

app/views/admin/admins/show.html.erb
<p id="notice"><%= notice %></p>
  <p><b>Email:</b><%= @admin.email %></p>
  <p><b>Role:</b><%= @admin.role %></p>
<%= link_to 'Edit', edit_admin_admin_path(@admin) %> |
<%= link_to 'Back', admin_admins_path %>