config/routes.rb
Conteo::Application.routes.draw do

  devise_for :users
  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'

  match '/api', to: 'home#api'

  match '/&fref=fb', to: 'home#index'
  match '/auth/:provider/callback', to: 'authentications#create'

  match '/casillas/:estado/:section', to: 'buscar_casillas#show', as: 'buscar_casillas_show'
  match '/casillas/buscar', to: 'buscar_casillas#new', via: :get


  resource :buscar_casillas, only: [:new, :show, :create], path: '/casillas/buscar'

  resources :exit_polls, only: :create
  resources :casillas, only: [:show, :update, :create] do
    resources :tickets, only: [:create], path: '/tickets/new'
  end

  resources :faltantes, only: [:index]

  match '/faltantes/:estado', to: 'faltantes#show', as: 'faltante'
  match '/faltantes/:estado/:page', to: 'faltantes#show', as: 'faltante'

  match '/verificacion', to: 'verificacion#show', as: 'verificacion'
  match '/verificacion/:id', to: 'verificacion#update', as: 'verificacion', via: :put

  namespace :admin do
    root to: 'panel#index'
    resources :verifications, only: :index
    resources :boxes do
      resource :results, only: [:show, :update, :create]
    end

    resources :result_images, only: :update

    resources :admins
    resources :tickets, only: [:index, :create, :update, :destroy]
  end

  namespace :api do
    resources :casillas, only: [:index, :show]
  end

  mount Resque::Server.new, :at => "/resque"
  match '/images/logo-desktop.png' => redirect('/assets/main-img.png')
end

app/controllers/admin/panel_controller.rb
class Admin::PanelController < Admin::BaseController

  def index
    @total = Box.to_verified.count
    @boxes = CasillasPresenter.new Box.to_verified.limit(50)
    @tickets = Ticket.to_attend.limit(10)
    @verified = Box.includes(:result).where('results.state = ?','verified').count
    @rejected = Box.includes(:result).where('results.state = ?','rejected').count
  end

end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  before_filter :require_user
  layout "admin"
  
  def index
  end

end

app/helpers/panel_helper.rb
module PanelHelper
end

app/views/admin/panel/index.html.haml
%h1
  Bienvenido al panel

.row-fluid
  .span6.well
    %h2
      Tickets

    %table.table.table-striped.table-bordered.table-condensed
      %thead
        %tr
          %th Id
          %th Incidencia
          %th Estado
          %th Acciones
      %tbody
        -@tickets.each do |ticket|
          %tr
            %td= ticket.id
            %td= ticket.issue
            %td= ticket.state.try(:humanize)
            %td
              %ul
                %li
                  = link_to 'Editar Casilla', edit_admin_box_path(ticket.ticketable.id)
                %li
                  = link_to 'Resultados casilla', admin_box_results_path(ticket.ticketable)
                %li
                  = link_to ticket.next_state.humanize, admin_ticket_path(ticket, next_state: ticket.next_state), method: :put if ticket.next_state

  .span6.well
    %h2
      Casillas a verificar

    .row-fluid
      .alert.alert-info.span6
        Casillas verificadas: #{@verified}
      .alert.alert-error.span6
        Casillas rechazadas: #{@rejected}

    .row-fluid
      .alert.span12
        Casillas por verificar #{@total}

    %table.table.table-striped.table-bordered.table-condensed
      %thead
        %tr
          %th Id
          %th Estado
          %th Sección
          %th Tipo
          %th Captura
          %th Acciones
      %tbody
        -@boxes.each do |box|
          %tr
            %td= box.id
            %td= box.state_name
            %td= box.section
            %td= box.kind
            %td= box.result.captured? ? 'Si' : 'No'
            %td
              %ul
                %li
                  = link_to 'Ver', [:admin, box]
                %li
                  = link_to 'Editar', edit_admin_box_path(box)
                %li
                  = link_to 'Resultados', admin_box_results_path(box)